<?php
$pageStart = 
'<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <title>MY WEBSITE PAGE</title>
        <link type="text/css" href="./local/jquery-ui-1.11.4/themes/ui-lightness/jquery-ui.min.css" rel="stylesheet" />
        <script type="text/javascript" src="./local/jquery-ui-1.11.4/external/jquery/jquery.js"></script>
        <script type="text/javascript" src="./local/jquery-ui-1.11.4/jquery-ui.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("#date1").datepicker();
            });
        </script>
    </head>
    
    <body>
        <h1>Hello, this is a template webpage generated by PHP!</h1>
        <div id="date1"></div>
        
    </body>
    
</html>';

print $pageStart;
?>