<?php
$pageStart = 
'<!DOCTYPE html>
<html lang="en">
<head>
<meta charset=utf-8" />
<title>MY WEBSITE PAGE</title>
<link type="text/css" href="./local/jquery-ui-1.11.4/themes/ui-lightness/jquery-ui.min.css" rel="stylesheet"  />
<script type="text/javascript" src="./local/jquery-ui-1.11.4/external/jquery/jquery.js"></script>
<script type="text/javascript" src="./local/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(e) {
        $("#date1").datepicker();
    });
</script>
</head>
<body>
<div id="date1"></div>
<p>Hello, this is a page generated by PHP!</p>
</body>
</html>';

print $pageStart;

?>